FROM php:8.2-apache

RUN a2enmod rewrite
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

COPY . /var/www/html
RUN chown -R www-data:www-data /var/www/html

# Tạo entrypoint tự build config.php theo ENV (không cần sửa file trong repo)
RUN cat > /usr/local/bin/docker-entrypoint.sh <<'EOF'
#!/bin/sh
set -e

CONFIG="/var/www/html/config.php"

# Backup config gốc trong image (nếu cần)
if [ -f "$CONFIG" ] && [ ! -f "/var/www/html/config.prod.php" ]; then
  cp "$CONFIG" /var/www/html/config.prod.php
fi

# Generate config chạy local theo ENV (bạn có thể dùng cho cả prod nếu muốn)
cat > "$CONFIG" <<PHP
<?php
// Generated by docker-entrypoint.sh

\$appEnv = getenv('APP_ENV') ?: 'local';
\$isProduction = (\$appEnv === 'production');

define('BASE_URL', getenv('BASE_URL') ?: 'http://localhost:8080');

define('DB_HOST', getenv('DB_HOST') ?: 'db');
define('DB_NAME', getenv('DB_NAME') ?: 'quanlytuyendungabc');
define('DB_USER', getenv('DB_USER') ?: 'root');
define('DB_PASS', getenv('DB_PASS') ?: 'example');

define('SMTP_HOST', getenv('SMTP_HOST') ?: 'smtp.gmail.com');
define('SMTP_PORT', (int)(getenv('SMTP_PORT') ?: 587));
define('SMTP_USER', getenv('SMTP_USER') ?: '');
define('SMTP_PASS', getenv('SMTP_PASS') ?: '');
define('SMTP_FROM_EMAIL', getenv('SMTP_FROM_EMAIL') ?: '');
define('SMTP_FROM_NAME', getenv('SMTP_FROM_NAME') ?: '');
PHP

exec apache2-foreground
EOF
CMD ["apache2-foreground"]

